services:
  - type: web
    name: ibu-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --config gunicorn.conf.py IBU_scraper:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false  # Set manually in Render dashboard